spring:
  application:
    name: learn-sc-config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/PatrickRoot/learn-spring-cloud
          search-paths: config
#          username:公开仓库不需要用户名
#          password:公开仓库不需要密码
server:
  port: 8888